"""Initial schema: scope_version, scope_rule, topic, topic_rule

Revision ID: 14632b60eb1e
Revises: 
Create Date: 2026-08-23 18:57:43.730565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14632b60eb1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scope_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_page', sa.String(length=255), nullable=False),
    sa.Column('revision_id', sa.BigInteger(), nullable=False),
    sa.Column('raw_json', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('activated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_page', 'revision_id')
    )
    op.create_table('topic',
    sa.Column('qid', sa.String(length=16), nullable=False),
    sa.Column('entity_class', sa.String(length=32), nullable=False),
    sa.Column('is_human', sa.Boolean(), nullable=False),
    sa.Column('is_living', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.Column('suppressed_reason', sa.Text(), nullable=True),
    sa.Column('suppressed_at', sa.DateTime(), nullable=True),
    sa.Column('suppressed_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('qid')
    )
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.create_index('ix_topic_is_living', ['is_living'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_suppressed'), ['suppressed'], unique=False)

    op.create_table('scope_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope_version_id', sa.Integer(), nullable=False),
    sa.Column('rule_key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('entity_class', sa.String(length=32), nullable=False),
    sa.Column('requires_reference', sa.Boolean(), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='risk_level'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('sparql_fragment', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['scope_version_id'], ['scope_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_version_id', 'rule_key')
    )
    op.create_table('topic_rule',
    sa.Column('topic_qid', sa.String(length=16), nullable=False),
    sa.Column('rule_key', sa.String(length=64), nullable=False),
    sa.Column('scope_version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic_qid'], ['topic.qid'], ),
    sa.PrimaryKeyConstraint('topic_qid', 'rule_key', 'scope_version_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_rule')
    op.drop_table('scope_rule')
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_suppressed'))
        batch_op.drop_index('ix_topic_is_living')

    op.drop_table('topic')
    op.drop_table('scope_version')
    # ### end Alembic commands ###
