"""M5: concept, term, term_evidence, term_assertion

Revision ID: 2dc0b0399879
Revises: fd8bd8b01a3c
Create Date: 2026-08-25 19:55:43.520474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc0b0399879'
down_revision = 'fd8bd8b01a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qid', sa.String(length=16), nullable=True),
    sa.Column('local_label', sa.String(length=255), nullable=True),
    sa.Column('lifecycle', sa.Enum('local', 'proposed', 'upstream', name='concept_lifecycle'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qid')
    )
    op.create_table('term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=20), nullable=False),
    sa.Column('written_form', sa.String(length=255), nullable=False),
    sa.Column('lexeme_id', sa.String(length=16), nullable=True),
    sa.Column('sense_id', sa.String(length=24), nullable=True),
    sa.Column('register', sa.Enum('neutral', 'clinical', 'outdated', 'slur', 'reclaimed', 'regional', 'unknown', name='term_register'), nullable=False),
    sa.Column('evidence_grade', sa.Enum('documented', 'organisational', 'community', 'single_report', name='term_evidence_grade'), nullable=False),
    sa.Column('lifecycle', sa.Enum('local', 'proposed', 'upstream', name='term_lifecycle'), nullable=False),
    sa.Column('upstream_ref', sa.String(length=24), nullable=True),
    sa.Column('usage_note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_id', 'language_code', 'written_form')
    )
    with op.batch_alter_table('term', schema=None) as batch_op:
        batch_op.create_index('ix_term_lang_register', ['language_code', 'register'], unique=False)

    op.create_table('term_assertion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('contributor', sa.String(length=255), nullable=False),
    sa.Column('agrees', sa.Boolean(), nullable=False),
    sa.Column('register_asserted', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_id', 'contributor')
    )
    op.create_table('term_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('publication', 'style_guide', 'dictionary', 'law', 'organisation', 'other', name='evidence_kind'), nullable=False),
    sa.Column('citation', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('org_name', sa.String(length=255), nullable=True),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('added_by', sa.String(length=255), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('term_evidence')
    op.drop_table('term_assertion')
    with op.batch_alter_table('term', schema=None) as batch_op:
        batch_op.drop_index('ix_term_lang_register')

    op.drop_table('term')
    op.drop_table('concept')
    # ### end Alembic commands ###
