"""M6: contributor_token, wiki_edit

Revision ID: 4b924db3132a
Revises: 2dc0b0399879
Create Date: 2026-08-25 20:38:14.483593

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b924db3132a'
down_revision = '2dc0b0399879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wiki_edit',
    sa.Column('id', sa.Integer().with_variant(mysql.BIGINT(), 'mysql'), nullable=False),
    sa.Column('contributor', sa.String(length=255), nullable=False),
    sa.Column('target_wiki', sa.String(length=64), nullable=False),
    sa.Column('target_entity', sa.String(length=64), nullable=False),
    sa.Column('edit_kind', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('revid', sa.Integer().with_variant(mysql.BIGINT(), 'mysql'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', 'blocked', name='wiki_edit_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wiki_edit', schema=None) as batch_op:
        batch_op.create_index('ix_wiki_edit_contributor_created', ['contributor', 'created_at'], unique=False)
        batch_op.create_index('ix_wiki_edit_created_at', ['created_at'], unique=False)

    op.create_table('contributor_token',
    sa.Column('contributor_id', sa.Integer(), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributor.id'], ),
    sa.PrimaryKeyConstraint('contributor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contributor_token')
    with op.batch_alter_table('wiki_edit', schema=None) as batch_op:
        batch_op.drop_index('ix_wiki_edit_created_at')
        batch_op.drop_index('ix_wiki_edit_contributor_created')

    op.drop_table('wiki_edit')
    # ### end Alembic commands ###
