"""M2: language, project, detector, gap

Revision ID: 822be768fd1c
Revises: 14632b60eb1e
Create Date: 2026-08-23 21:03:04.675455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = '822be768fd1c'
down_revision = '14632b60eb1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detector_key', sa.String(length=64), nullable=False),
    sa.Column('project_code', sa.String(length=32), nullable=False),
    sa.Column('gap_type', sa.String(length=64), nullable=False),
    sa.Column('maturity', sa.Enum('stable', 'beta', 'experimental', name='detector_maturity'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('detector_key')
    )
    op.create_table('gap',
    sa.Column('id', sa.Integer().with_variant(mysql.BIGINT(), "mysql"), nullable=False),
    sa.Column('topic_qid', sa.String(length=16), nullable=False),
    sa.Column('language_code', sa.String(length=20), nullable=False),
    sa.Column('project_code', sa.String(length=32), nullable=False),
    sa.Column('gap_type', sa.String(length=64), nullable=False),
    sa.Column('detector_key', sa.String(length=64), nullable=False),
    sa.Column('scope_version_id', sa.Integer(), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('action_url', sa.Text(), nullable=True),
    sa.Column('impact_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_qid', 'language_code', 'project_code', 'gap_type')
    )
    with op.batch_alter_table('gap', schema=None) as batch_op:
        batch_op.create_index('ix_gap_impact_score', ['impact_score'], unique=False)
        batch_op.create_index('ix_gap_lang_project_type', ['language_code', 'project_code', 'gap_type'], unique=False)

    op.create_table('language',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('autonym', sa.String(length=128), nullable=False),
    sa.Column('seeded', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('project',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('family', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###

    # Seed data: the initial content-language and project set Duga tracks.
    # Not fetched from anywhere -- an editorial choice, expanded later with
    # plain INSERTs (see docs/architecture.md). Kept minimal on purpose: M2
    # only needs one project (wikipedia, for wp_no_article) and two
    # languages to prove the pipeline end to end.
    language = sa.table(
        'language',
        sa.column('code', sa.String),
        sa.column('autonym', sa.String),
        sa.column('seeded', sa.Boolean),
    )
    op.bulk_insert(language, [
        {'code': 'sr', 'autonym': 'Српски', 'seeded': True},
        {'code': 'fr', 'autonym': 'Français', 'seeded': True},
    ])

    project = sa.table(
        'project',
        sa.column('code', sa.String),
        sa.column('family', sa.String),
    )
    op.bulk_insert(project, [
        {'code': 'wikipedia', 'family': 'wikipedia'},
    ])


def downgrade():
    op.execute("DELETE FROM language WHERE code IN ('sr', 'fr')")
    op.execute("DELETE FROM project WHERE code = 'wikipedia'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    op.drop_table('language')
    with op.batch_alter_table('gap', schema=None) as batch_op:
        batch_op.drop_index('ix_gap_lang_project_type')
        batch_op.drop_index('ix_gap_impact_score')

    op.drop_table('gap')
    op.drop_table('detector')
    # ### end Alembic commands ###
