"""M3: gap_override, wikidata project

Revision ID: d4cbd1b828f3
Revises: 822be768fd1c
Create Date: 2026-08-23 22:07:30.818161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd4cbd1b828f3'
down_revision = '822be768fd1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gap_override',
    sa.Column('id', sa.Integer().with_variant(mysql.BIGINT(), 'mysql'), nullable=False),
    sa.Column('topic_qid', sa.String(length=16), nullable=False),
    sa.Column('language_code', sa.String(length=20), nullable=False),
    sa.Column('project_code', sa.String(length=32), nullable=False),
    sa.Column('gap_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('declined', 'not_applicable', 'done', name='gap_override_status'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('set_by', sa.String(length=255), nullable=False),
    sa.Column('set_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_qid', 'language_code', 'project_code', 'gap_type')
    )
    # ### end Alembic commands ###

    project = sa.table('project', sa.column('code', sa.String), sa.column('family', sa.String))
    op.bulk_insert(project, [
        {'code': 'wikidata', 'family': 'wikidata'},
    ])


def downgrade():
    op.execute("DELETE FROM project WHERE code = 'wikidata'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gap_override')
    # ### end Alembic commands ###
