"""M4: contributor, audit_log

Revision ID: fd8bd8b01a3c
Revises: d4cbd1b828f3
Create Date: 2026-08-23 22:37:16.443387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd8bd8b01a3c'
down_revision = 'd4cbd1b828f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer().with_variant(mysql.BIGINT(), 'mysql'), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('before_json', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('after_json', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_log_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_audit_log_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('contributor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wiki_username', sa.String(length=255), nullable=False),
    sa.Column('display_public', sa.Boolean(), nullable=False),
    sa.Column('languages_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wiki_username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contributor')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_log_entity')
        batch_op.drop_index('ix_audit_log_created_at')

    op.drop_table('audit_log')
    # ### end Alembic commands ###
